
services:
  app:
    build: ./app
    ports: 
      - "5173:5173"
    volumes:
      - web-root:/app/public
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  server:
    build: ./server
    ports: 
      - "5050:5050"
    depends_on: 
      - mongo
    networks: 
      - app-networks
    volumes:
      - web-root:/server/public

  mongo:
    image: mongo:7.0.8
    networks:
      - app-networks
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017

networks:
  app-networks:
    driver: bridge

volumes:
  data-volume:
  node-modules:
  web-root:
    driver: local

